feat: stage encounters model
mkryed/dbt_demo_healthcare pull request #5
Opened 2023-06-06 19:37 UTC by mkryed

## Description & motivation
Created stg_encounters.sql and stg_encounters.yml file

## Checklist:

- [x] My pull request represents one logical piece of work.
- [x] My commits are related to the pull request and look clean.
- [x] My SQL follows the [dbt Labs style guide](https://github.com/dbt-labs/corp/blob/master/dbt_style_guide.md).
- [x] I have materialized my models appropriately.
- [x] I have added appropriate tests and documentation to any new models.
- [ ] I have updated the README file.
- [ ] I have mask the PII data.

2023-06-06 19:59 UTC, 90awlui commented on models/marts/staging/stg_encounters.sql
> +
is there normally a blank line at the top of files?

2023-06-06 19:59 UTC, 90awlui commented on models/marts/staging/stg_encounters.yml
> +        description: Primary Key for encounters records
Since you're the first to do a PR with the id descriptions can you create a doc blocks .md file with the descriptions for each of the ids? e.g.

```
{% docs encounters_id %}
The unique identifier for patient encounters. An encounter is ...
{% enddocs %}

{% docs patient_id %}
...
```

2023-06-06 19:59 UTC, 90awlui commented on models/marts/staging/stg_encounters.yml
> +        description: Foreign key that connects to patients table
Not anything to do now but when all the staging tables are in we can do relationship tests for the foreign keys

2023-06-06 23:21 UTC, mkryed commented on models/marts/staging/stg_encounters.sql
> +
Sorry for that. Just corrected it. Ready for review in the next commit

2023-06-06 23:21 UTC, mkryed commented on models/marts/staging/stg_encounters.yml
> +        description: Primary Key for encounters records
docs file has been added and ready for review!

2023-06-07 14:53 UTC, 90awlui submitted a review, later dismissed
approve, there's going to be a ticket to amalgamate the .md files later

2023-06-07 14:56 UTC, 90awlui requested changes
I checked and your condition_id and procedure_id columns are both blank. are there any condition_id or procedure_id columns that aren't blank in the data source? If not, I think you can exclude these columns

2023-06-07 15:30 UTC, 90awlui approved these changes

2023-06-07 15:30 UTC, merged