Feat stg organizations
mkryed/dbt_demo_healthcare pull request #6
Opened 2023-06-06 21:15 UTC by Devashree-Patel

## Description & motivation

## To-do before merge

## Screenshots:

## Validation of models:

## Changes to existing models:

## Checklist:

- [ ] My pull request represents one logical piece of work.
- [ ] My commits are related to the pull request and look clean.
- [ ] My SQL follows the [dbt Labs style guide](https://github.com/dbt-labs/corp/blob/master/dbt_style_guide.md).
- [ ] I have materialized my models appropriately.
- [ ] I have added appropriate tests and documentation to any new models.
- [ ] I have updated the README file.
- [ ] I have mask the PII data.

2023-06-06 21:50 UTC, 90awlui requested changes

2023-06-06 21:50 UTC, 90awlui commented on models/docs/healthcare_demo.md
> +Healthcare organization details
```suggestion
A formally or informally recognized grouping of people or organizations formed for the purpose of achieving some form of collective action. Includes companies, institutions, corporations, departments, community groups, healthcare practice groups, payer/insurer, etc.

source: https://www.hl7.org/fhir/organization.html
```

2023-06-06 21:50 UTC, 90awlui commented on models/docs/healthcare_demo.md
> + A unique identifier for the organization.
```suggestion
A unique identifier for the organization
```

2023-06-06 21:50 UTC, 90awlui commented on models/docs/healthcare_demo.md
> +The name of the organization.
```suggestion
The name of the organization
```

2023-06-06 21:50 UTC, 90awlui commented on models/marts/staging/stg_organizations.sql
> +    address.country,
I think these should also be prefixed with `organization_` e.g. `organization_city`

2023-06-06 21:50 UTC, 90awlui commented on models/marts/staging/stg_organizations.sql
> +    address.postalcode
should be postal_code (2 words)

2023-06-06 21:50 UTC, 90awlui commented on models/marts/staging/stg_organizations.yml
> +          description: "{{ doc('organization_id') }}"
should include not_null and unique tests

2023-06-06 21:50 UTC, 90awlui commented on models/marts/staging/stg_organizations.sql
> +    type.text as organization_type,
can this be `type[SAFE_OFFSET(0)].text` instead of doing a cross join unnest?

2023-06-06 21:50 UTC, 90awlui commented on models/marts/staging/stg_organizations.sql
> +cross join unnest(organizations.address) as address
similar to above, can we just directly access `address` values through `address[SAFE_OFFSET(0)].line` etc. rather than doing a cross join?

2023-06-06 21:50 UTC, 90awlui commented on models/marts/staging/stg_organizations.sql
> +select
this select should be indented

2023-06-07 01:51 UTC, Devashree-Patel commented on models/marts/staging/stg_organizations.sql
> +select
Changes done

2023-06-07 02:12 UTC, Devashree-Patel commented on models/marts/staging/stg_organizations.sql
> +    address.country,
Yes I had those changes forgot to save the file while committing. It's updated now.

2023-06-07 02:12 UTC, Devashree-Patel commented on models/marts/staging/stg_organizations.sql
> +    address.postalcode
Done

2023-06-07 02:13 UTC, Devashree-Patel commented on models/marts/staging/stg_organizations.yml
> +          description: "{{ doc('organization_id') }}"
Done

2023-06-07 02:21 UTC, Devashree-Patel commented on models/marts/staging/stg_organizations.sql
> +    type.text as organization_type,
I don't think they mean the same. When I am using offset most of columns are showing up as null. Check out these querys on big query and let me know your thoughts

select
        --primary key
        id as organization_id,
        --strings
        name as organization_name,
        type.text as organization_type,
        address.line as organization_address,
        address.city as organization_city,
        address.state as organization_state,
        address.country as organization_country,
        address.postalcode as organization_postal_code
    from  `datatonic-americas-demos.fhir_synthea_raw.organizations_view` organizations
    cross join unnest(organizations.type) as type
    cross join unnest(organizations.address) as address


select * from `datatonic-americas-demos.fhir_synthea_raw.organizations_view` where id = 'ac8356a5-78f8-3a63-8a1e-59e832fd54e7'

select
        --primary key
        id as organization_id,
        --strings
        name as organization_name,
        type[SAFE_OFFSET(1)].text as organization_type,
        address[SAFE_OFFSET(7)].line as organization_address,
        address[SAFE_OFFSET(5)].city as organization_city,
        address[SAFE_OFFSET(9)].state as organization_state,
        address[SAFE_OFFSET(6)].country as organization_country,
        address[SAFE_OFFSET(8)].postalcode as organization_postal_code
    from  `datatonic-americas-demos.fhir_synthea_raw.organizations_view` organizations

2023-06-07 14:29 UTC, 90awlui commented on models/marts/staging/stg_organizations.sql
> +    type.text as organization_type,
I think you might be misinterpreting the type/address data structure or the SAFE_OFFSET function. 

Address is a json and would look something like this 
```
{
  'district': string,
  'period': {},
  'text': string,
  'line': string,
}
```
So you wouldn't need anything other than 0 for your SAFE_OFFSET. This would be a different story if address were an array and were something like this where the index mattered.
```
[district, period, text, line]
```

This returns to me what I would expect 
```
select
  type[SAFE_OFFSET(0)].text,
  address[SAFE_OFFSET(0)].line,
  address[SAFE_OFFSET(0)].city,
  address[SAFE_OFFSET(0)].state,
  address[SAFE_OFFSET(0)].country,
  address[SAFE_OFFSET(0)].postalCode
from datatonic-americas-demos.fhir_synthea_raw.organizations_view 
where id = 'ac8356a5-78f8-3a63-8a1e-59e832fd54e7'
```

2023-06-07 14:31 UTC, Devashree-Patel commented on models/docs/healthcare_demo.md
> +Healthcare organization details
Done

2023-06-07 16:18 UTC, Devashree-Patel commented on models/marts/staging/stg_organizations.sql
> +    type.text as organization_type,
Makes sense. Yes I did misinterpret it. I have made changes now

2023-06-07 16:18 UTC, Devashree-Patel commented on models/marts/staging/stg_organizations.sql
> +cross join unnest(organizations.address) as address
Changes done

2023-06-07 18:31 UTC, 90awlui approved these changes

2023-06-07 18:37 UTC, merged